version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB=sprint5
      - DB_USER=igorribeiro
      - SECRET_KEY=KImoveis3%#-h9!ps8msv7xp3i&mbg9^@6cqe99aehn%z97=k^40axlez9KenzieAcademy
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=igorribeiro
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sprint5
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U igorribeiro -d sprint5']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
